version: "3.6"

services:
  server:
    image: server
    build:
      context: ./docker/server
      args:
        - USER=${USER-splice}
        - GROUP=${GROUP-splice}
        - APACHE_RUN_USER=${USER-splice}
        - APACHE_RUN_GROUP=${GROUP-splice}
    environment:
      - USER=${USER-splice}
      - GROUP=${GROUP-splice}
      - APACHE_RUN_USER=${USER-splice}
      - APACHE_RUN_GROUP=${GROUP-splice}
    container_name: ${PROJECT}-server
    restart: 'always'
    ports:
      - ${PORT_HTTP}:80
      - ${PORT_HTTPS}:443
    links:
      - mysql
    volumes:
      - ${DOCUMENT_ROOT-./www}:/var/www/html
      - ${DOCUMENT_ROOT-./var/utility}:/var/www/utility
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
      - ${BIN_DIR-./bin}:/home/${USER}/bin
  mysql:
    image: mysql
    build: ./docker/mysql
    container_name: ${PROJECT}-mysql
    restart: 'always'
    ports:
      - ${PORT_MYSQL}:3306
    volumes:
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: splice
      MYSQL_USER: root
      MYSQL_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${PROJECT}-phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - ${PORT_PHPMYADMIN}:80
    volumes:
      - /sessions
  redis:
    container_name: ${PROJECT}-redis
    image: redis:latest
    ports:
      - ${PORT_REDIS}:6379
