#!/bin/bash
cd $(dirname $0)/..

read -p "Are you sure you want to rebuild? This may take a long time." -n 1 -r
echo    # (optional) move to a new line
if [[ $REPLY =~ ^[Yy]$ ]]
then
    docker-compose build --build-arg USER=$USER --build-arg GROUP=$(id -gn) --no-cache
fi
